# Generated by Django 4.2.4 on 2023-08-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='Изображение'),
        ),
    ]
