# Generated by Django 4.2.4 on 2023-08-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_file_anons_alter_file_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='con_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('anons', models.CharField(max_length=200, verbose_name='Анонс')),
            ],
        ),
    ]
