# Generated by Django 4.2.4 on 2023-08-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_con_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='con_data',
            new_name='Сon_data',
        ),
    ]
